name: jim
favicon: null
layout_spectrum: 0.41148424125276506
typography_spectrum: 0.14535921486094594
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8679138284642249
  lightness: 0.3610539175570011
  saturation: 0.032782602589577436
  rhythmicContrast: 0.048433825839310884
purpose: []
